### ISSUE TITLE
Grammar in Section 1.2

### ISSUE THREAD

**Issue by kopeckyf** [langsci/353#539]
In Section 1.2, you write

https://github.com/langsci/353/blob/5ef996cc0c1ef6010557c4c079e14ce1e5ac6932/chapters/germanic-overview.tex#L58

I believe that “on the Crimean peninsula” or “in Crimea” might be correct but that “on the Crimea” might not be.

**Comment by stefan11** [comment]
But it was proofread by native speakers.

**Comment by stefan11** [comment]
Thanks!

**Comment by kopeckyf** [comment]
Have you looked at corpus results for `"on the Crimea"`? It doesn't seem to me like this phrase is used like German _auf der Krim_. But I don't have any Aktien in it.

**Comment by stefan11** [comment]
Yes, you are right. I already said thank you. =:-)
